#用户数据
CREATE TABLE USER(
    USERID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    USER VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR (255) NOT NULL,
    MONEY DOUBLE
);
#存储书籍数据
CREATE TABLE BOOK(
    BOOKID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    BOOKNAME VARCHAR(255) NOT NULL,
    AUTHOR VARCHAR(255),
    BOOKPRICE DOUBLE NOT NULL,
    BOOKAMOUNT INT NOT NULL

);
#用户数据子表,用于存储用户的相关属性数据
CREATE TABLE USERDATA(
    USERDATAID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR(255) NOT NULL,
    SEX INT NOT NULL,
    AGE INT NOT NULL,
    EMAIL VARCHAR(255)
);
